#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Jan 22, 2021 05:31:30 PM +0200  platform: Windows NT
#    Jan 22, 2021 05:46:38 PM +0200  platform: Windows NT
#    Jan 22, 2021 06:05:26 PM +0200  platform: Windows NT

import sys
import sqlite3
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def btnExit_1click(p1):
    print('Main_support.btnExit_1click')
    sys.stdout.flush()
    destroy_window()
def btn_1click(p1):
    print('Main_support.btn_1click')
    sys.stdout.flush()
    import SignUp
    SignUp.create_SignUp(root,'Hello',top_level)

def btnLog_1click(p1):
    print('Main_support.btnLog_1click')
    sys.stdout.flush()
    import LogIn
    LogIn.create_LogIn(root,'Hello',top_level)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Main
    Main.vp_start_gui()





