#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Jan 22, 2021 06:37:47 PM +0200  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import SignUp_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    SignUp_support.set_Tk_var()
    top = SignUp (root)
    SignUp_support.init(root, top)
    root.mainloop()

w = None
def create_SignUp(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_SignUp(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    SignUp_support.set_Tk_var()
    top = SignUp (w)
    SignUp_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_SignUp():
    global w
    w.destroy()
    w = None

class SignUp:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+660+210")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("SignUp")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.EntUser = tk.Entry(top)
        self.EntUser.place(relx=0.45, rely=0.222, height=20, relwidth=0.14)
        self.EntUser.configure(background="white")
        self.EntUser.configure(disabledforeground="#a3a3a3")
        self.EntUser.configure(font="TkFixedFont")
        self.EntUser.configure(foreground="#000000")
        self.EntUser.configure(highlightbackground="#d9d9d9")
        self.EntUser.configure(highlightcolor="black")
        self.EntUser.configure(insertbackground="black")
        self.EntUser.configure(selectbackground="blue")
        self.EntUser.configure(selectforeground="white")

        self.lblSign = tk.Label(top)
        self.lblSign.place(relx=0.417, rely=0.067, height=41, width=104)
        self.lblSign.configure(activebackground="#f9f9f9")
        self.lblSign.configure(activeforeground="black")
        self.lblSign.configure(background="#d9d9d9")
        self.lblSign.configure(disabledforeground="#a3a3a3")
        self.lblSign.configure(foreground="#000000")
        self.lblSign.configure(highlightbackground="#d9d9d9")
        self.lblSign.configure(highlightcolor="black")
        self.lblSign.configure(text='''SignUp''')

        self.LblUsr = tk.Label(top)
        self.LblUsr.place(relx=0.317, rely=0.222, height=21, width=74)
        self.LblUsr.configure(activebackground="#f9f9f9")
        self.LblUsr.configure(activeforeground="black")
        self.LblUsr.configure(background="#d9d9d9")
        self.LblUsr.configure(disabledforeground="#a3a3a3")
        self.LblUsr.configure(foreground="#000000")
        self.LblUsr.configure(highlightbackground="#d9d9d9")
        self.LblUsr.configure(highlightcolor="black")
        self.LblUsr.configure(text='''Username''')

        self.EntPass = tk.Entry(top)
        self.EntPass.place(relx=0.45, rely=0.311, height=20, relwidth=0.14)
        self.EntPass.configure(background="white")
        self.EntPass.configure(disabledforeground="#a3a3a3")
        self.EntPass.configure(font="TkFixedFont")
        self.EntPass.configure(foreground="#000000")
        self.EntPass.configure(highlightbackground="#d9d9d9")
        self.EntPass.configure(highlightcolor="black")
        self.EntPass.configure(insertbackground="black")
        self.EntPass.configure(selectbackground="blue")
        self.EntPass.configure(selectforeground="white")

        self.LblPass = tk.Label(top)
        self.LblPass.place(relx=0.317, rely=0.311, height=21, width=74)
        self.LblPass.configure(activebackground="#f9f9f9")
        self.LblPass.configure(activeforeground="black")
        self.LblPass.configure(background="#d9d9d9")
        self.LblPass.configure(disabledforeground="#a3a3a3")
        self.LblPass.configure(foreground="#000000")
        self.LblPass.configure(highlightbackground="#d9d9d9")
        self.LblPass.configure(highlightcolor="black")
        self.LblPass.configure(text='''Password''')

        self.Checkbutton1 = tk.Checkbutton(top)
        self.Checkbutton1.place(relx=0.45, rely=0.4, relheight=0.1
                , relwidth=0.135)
        self.Checkbutton1.configure(activebackground="#ececec")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(background="#d9d9d9")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(text='''Student''')
        self.Checkbutton1.configure(variable=SignUp_support.che50)

        self.Checkbutton2 = tk.Checkbutton(top)
        self.Checkbutton2.place(relx=0.45, rely=0.489, relheight=0.1
                , relwidth=0.135)
        self.Checkbutton2.configure(activebackground="#ececec")
        self.Checkbutton2.configure(activeforeground="#000000")
        self.Checkbutton2.configure(background="#d9d9d9")
        self.Checkbutton2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2.configure(foreground="#000000")
        self.Checkbutton2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton2.configure(highlightcolor="black")
        self.Checkbutton2.configure(justify='left')
        self.Checkbutton2.configure(text='''Teacher''')
        self.Checkbutton2.configure(variable=SignUp_support.che51)

        self.BtnConfirm = tk.Button(top)
        self.BtnConfirm.place(relx=0.467, rely=0.644, height=34, width=57)
        self.BtnConfirm.configure(activebackground="#ececec")
        self.BtnConfirm.configure(activeforeground="#000000")
        self.BtnConfirm.configure(background="#d9d9d9")
        self.BtnConfirm.configure(cursor="fleur")
        self.BtnConfirm.configure(disabledforeground="#a3a3a3")
        self.BtnConfirm.configure(foreground="#000000")
        self.BtnConfirm.configure(highlightbackground="#d9d9d9")
        self.BtnConfirm.configure(highlightcolor="black")
        self.BtnConfirm.configure(pady="0")
        self.BtnConfirm.configure(text='''Confirm''')
        self.BtnConfirm.bind('<Button-1>',lambda e:SignUp_support.btnConfirm_1click(e))

if __name__ == '__main__':
    vp_start_gui()





