#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 28, 2021 01:18:49 PM +0200  platform: Windows NT
import datetime
from threading import *
import sys
from socket import *
from time import sleep
import Main_support
import LogIn_support
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

    
    
    
from queue import Queue

conn_q = Queue()
gui_q  = Queue()




def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    global LogIn       
    LogIn = args[1] 
    LogIn.withdraw()
    user=LogIn_support.User1()
    w.UserDetails.insert(tk.END, user.Username)
    x = datetime.datetime.now()
    w.ClassDetails.insert(tk.END, x.strftime("%x"))
    conn_q.put("Get")
    sendThead = Thread(target=client_send, args=())
    sendThead.start()
    recThead = Thread(target=client_rec, args=())
    recThead.start()
    GetThead = Thread(target=send_Get, args=())
    GetThead.start()

def Exit_Click(p1):
    print('Student_support.Exit_Click')
    sys.stdout.flush()
    destroy_window()
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def client_send():
    while True:
        if conn_q.empty() == False:
            data = conn_q.get()
            print ("client_send:" + data )
            print("3333",current_thread().name)
            Main_support.my_socket.sendall(data.encode('latin-1'))
        sleep(0.05) #sleep a little before check the queue again

def client_rec():
    global w
    while (1):
        data = Main_support.my_socket.recv(1024)
        data = data.decode('utf-8')
        print("server response: " + data)
        w.Schedule.delete('1.0', tk.END)
        w.Schedule.insert(tk.END,data)

def send_Get():
    while(1):
        conn_q.put("Get")
        sleep(5)



if __name__ == '__main__':
    import Student
    Student.vp_start_gui()





