#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 28, 2021 01:18:49 PM +0200  platform: Windows NT

from threading import *
import sys
from socket import *
from time import sleep

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

    
    
    
from queue import Queue

conn_q = Queue()
gui_q  = Queue()




def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    global LogIn       
    LogIn = args[1] 
    LogIn.withdraw()
    conn_q.put("Get")




def Exit_Click(p1):
    print('Student_support.Exit_Click')
    sys.stdout.flush()
    destroy_window()
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


class client_send(Thread):
    def __init__(self, client_socket):
        Thread.__init__(self)
        self.my_socket = client_socket

    def run(self):
        while True:
            if conn_q.empty() == False:
                msg = conn_q.get()
                msg = msg.encode()
                self.my_socket.send(msg)
            sleep(0.02)  # sleep 20 ms - let the cpu breath




if __name__ == '__main__':
    import Student
    Student.vp_start_gui()





