#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Jun 13, 2021 04:30:13 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Student_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Student (root)
    Student_support.init(root, top)
    root.mainloop()

w = None
def create_Student(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Student(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Student (w)
    Student_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Student():
    global w
    w.destroy()
    w = None

class Student:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+660+210")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Online Class")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Title = tk.Label(top)
        self.Title.place(relx=0.383, rely=0.044, height=41, width=124)
        self.Title.configure(activebackground="#f9f9f9")
        self.Title.configure(activeforeground="black")
        self.Title.configure(background="#d9d9d9")
        self.Title.configure(disabledforeground="#a3a3a3")
        self.Title.configure(foreground="#000000")
        self.Title.configure(highlightbackground="#d9d9d9")
        self.Title.configure(highlightcolor="black")
        self.Title.configure(text='''Label''')

        self.UserDetails = tk.Text(top)
        self.UserDetails.place(relx=0.017, rely=0.022, relheight=0.142
                , relwidth=0.307)
        self.UserDetails.configure(background="white")
        self.UserDetails.configure(font="TkTextFont")
        self.UserDetails.configure(foreground="black")
        self.UserDetails.configure(highlightbackground="#d9d9d9")
        self.UserDetails.configure(highlightcolor="black")
        self.UserDetails.configure(insertbackground="black")
        self.UserDetails.configure(selectbackground="blue")
        self.UserDetails.configure(selectforeground="white")
        self.UserDetails.configure(wrap="word")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.067, rely=0.244, relheight=0.678
                , relwidth=0.508)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Schedule = tk.Text(self.Frame1)
        self.Schedule.place(relx=0.033, rely=0.098, relheight=0.872
                , relwidth=0.934)
        self.Schedule.configure(background="white")
        self.Schedule.configure(font="TkTextFont")
        self.Schedule.configure(foreground="black")
        self.Schedule.configure(highlightbackground="#d9d9d9")
        self.Schedule.configure(highlightcolor="black")
        self.Schedule.configure(insertbackground="black")
        self.Schedule.configure(selectbackground="blue")
        self.Schedule.configure(selectforeground="white")
        self.Schedule.configure(state='normal')
        self.Schedule.configure(wrap="word")

        self.FrameTitle = tk.Label(top)
        self.FrameTitle.place(relx=0.267, rely=0.244, height=21, width=74)
        self.FrameTitle.configure(activebackground="#f9f9f9")
        self.FrameTitle.configure(activeforeground="black")
        self.FrameTitle.configure(background="#d9d9d9")
        self.FrameTitle.configure(disabledforeground="#a3a3a3")
        self.FrameTitle.configure(foreground="#000000")
        self.FrameTitle.configure(highlightbackground="#d9d9d9")
        self.FrameTitle.configure(highlightcolor="black")
        self.FrameTitle.configure(text='''Schedule''')

        self.ClassDetails = tk.Text(top)
        self.ClassDetails.place(relx=0.65, rely=0.022, relheight=0.142
                , relwidth=0.257)
        self.ClassDetails.configure(background="white")
        self.ClassDetails.configure(font="TkTextFont")
        self.ClassDetails.configure(foreground="black")
        self.ClassDetails.configure(highlightbackground="#d9d9d9")
        self.ClassDetails.configure(highlightcolor="black")
        self.ClassDetails.configure(insertbackground="black")
        self.ClassDetails.configure(selectbackground="blue")
        self.ClassDetails.configure(selectforeground="white")
        self.ClassDetails.configure(wrap="word")

        self.Exit = tk.Button(top)
        self.Exit.place(relx=0.733, rely=0.8, height=44, width=67)
        self.Exit.configure(activebackground="#ececec")
        self.Exit.configure(activeforeground="#000000")
        self.Exit.configure(background="#d9d9d9")
        self.Exit.configure(disabledforeground="#a3a3a3")
        self.Exit.configure(foreground="#000000")
        self.Exit.configure(highlightbackground="#d9d9d9")
        self.Exit.configure(highlightcolor="black")
        self.Exit.configure(pady="0")
        self.Exit.configure(text='''Exit''')
        self.Exit.bind('<Button-1>',lambda e:Student_support.Exit_Click(e))

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.617, rely=0.244, relheight=0.544
                , relwidth=0.342)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.FrameTitle2 = tk.Label(self.Frame2)
        self.FrameTitle2.place(relx=0.244, rely=0.045, height=23, width=104)
        self.FrameTitle2.configure(activebackground="#f9f9f9")
        self.FrameTitle2.configure(activeforeground="black")
        self.FrameTitle2.configure(background="#d9d9d9")
        self.FrameTitle2.configure(disabledforeground="#a3a3a3")
        self.FrameTitle2.configure(foreground="#000000")
        self.FrameTitle2.configure(highlightbackground="#d9d9d9")
        self.FrameTitle2.configure(highlightcolor="black")
        self.FrameTitle2.configure(text='''Chat''')

        self.Chat = tk.Text(self.Frame2)
        self.Chat.place(relx=0.049, rely=0.18, relheight=0.771, relwidth=0.898)
        self.Chat.configure(background="white")
        self.Chat.configure(font="TkTextFont")
        self.Chat.configure(foreground="black")
        self.Chat.configure(highlightbackground="#d9d9d9")
        self.Chat.configure(highlightcolor="black")
        self.Chat.configure(insertbackground="black")
        self.Chat.configure(selectbackground="blue")
        self.Chat.configure(selectforeground="white")
        self.Chat.configure(wrap="word")

if __name__ == '__main__':
    vp_start_gui()





