#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Jun 13, 2021 04:29:45 PM +0300  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+660+210
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Online Class"
    vTcl:DefineAlias "$top" "Student" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$top.lab45" "Title" vTcl:WidgetProc "Student" 1
    text $top.tex47 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 184 -wrap word 
    $top.tex47 configure -font "TkTextFont"
    $top.tex47 insert end text
    vTcl:DefineAlias "$top.tex47" "UserDetails" vTcl:WidgetProc "Student" 1
    frame $top.fra48 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 305 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 305 
    vTcl:DefineAlias "$top.fra48" "Frame1" vTcl:WidgetProc "Student" 1
    set site_3_0 $top.fra48
    text $site_3_0.tex50 \
        -background white -font TkTextFont -foreground black -height 266 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state disabled -width 285 -wrap word 
    $site_3_0.tex50 configure -font "TkTextFont"
    $site_3_0.tex50 insert end text
    vTcl:DefineAlias "$site_3_0.tex50" "Schedule" vTcl:WidgetProc "Student" 1
    place $site_3_0.tex50 \
        -in $site_3_0 -x 0 -relx 0.033 -y 0 -rely 0.098 -width 0 \
        -relwidth 0.934 -height 0 -relheight 0.872 -anchor nw \
        -bordermode ignore 
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Schedule 
    vTcl:DefineAlias "$top.lab49" "FrameTitle" vTcl:WidgetProc "Student" 1
    text $top.tex52 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 154 -wrap word 
    $top.tex52 configure -font "TkTextFont"
    $top.tex52 insert end text
    vTcl:DefineAlias "$top.tex52" "ClassDetails" vTcl:WidgetProc "Student" 1
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Exit 
    vTcl:DefineAlias "$top.but53" "Exit" vTcl:WidgetProc "Student" 1
    bind $top.but53 <Button-1> {
        lambda e: Exit_Click(e)
    }
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 245 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 205 
    vTcl:DefineAlias "$top.fra46" "Frame2" vTcl:WidgetProc "Student" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Chat 
    vTcl:DefineAlias "$site_3_0.lab47" "FrameTitle2" vTcl:WidgetProc "Student" 1
    text $site_3_0.tex48 \
        -background white -font TkTextFont -foreground black -height 174 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 184 -wrap word 
    $site_3_0.tex48 configure -font "TkTextFont"
    $site_3_0.tex48 insert end text
    vTcl:DefineAlias "$site_3_0.tex48" "Chat" vTcl:WidgetProc "Student" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.244 -y 0 -rely 0.044 -width 0 \
        -relwidth 0.507 -height 0 -relheight 0.093 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex48 \
        -in $site_3_0 -x 0 -relx 0.049 -y 0 -rely 0.178 -width 0 \
        -relwidth 0.898 -height 0 -relheight 0.773 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 0 -relx 0.383 -y 0 -rely 0.044 -width 0 -relwidth 0.207 \
        -height 0 -relheight 0.091 -anchor nw -bordermode ignore 
    place $top.tex47 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.022 -width 0 -relwidth 0.307 \
        -height 0 -relheight 0.142 -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.244 -width 0 -relwidth 0.508 \
        -height 0 -relheight 0.678 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.267 -y 0 -rely 0.244 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.tex52 \
        -in $top -x 0 -relx 0.65 -y 0 -rely 0.022 -width 0 -relwidth 0.257 \
        -height 0 -relheight 0.142 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.733 -y 0 -rely 0.8 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.244 -width 0 -relwidth 0.342 \
        -height 0 -relheight 0.544 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

