#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Mar 01, 2021 05:06:52 PM +0200  platform: Windows NT
#    Mar 01, 2021 05:09:45 PM +0200  platform: Windows NT
from threading import *
import sys
from socket import *
from time import sleep
from queue import Queue

conn_q = Queue()
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    global LogIn       
    LogIn = args[1] 
    LogIn.withdraw()
def Exit_Click(p1):
    print('Teacher_support.Exit_Click')
    sys.stdout.flush()
    destroy_window()
def Send_Click(p1):
    print('Teacher_support.Send_Click')
    #send_message()
    sys.stdout.flush()
    
    
    
def send_message(p1):
    global w
    print('gui_chat_support.send_message')
    print("111")
    date=w.Date.get()
    time=w.Time.get()
    classType=w.ClassType.get()
    content=w.Content.get()
    s=date+","+time+","+classType+","+content
    #to = w.Scrolledtext1
    #to.insert(END,s)
    conn_q.put(s)
    #sys.stdout.flush()
 

def client_send(): 
    while True:
        if conn_q.empty() == False:
            data = conn_q.get()
            print ("client_send:" + data )
            print("3333",current_thread().name)
            my_socket.sendall(data.encode('latin-1'))
        sleep(0.05) #sleep a little before check the queue again
    
    
    
    
    
    
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Teacher
    Teacher.vp_start_gui()





