#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Mar 01, 2021 05:09:39 PM +0200  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+621+233
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Online Class"
    vTcl:DefineAlias "$top" "Teacher_first" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    text $top.tex45 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 -wrap word 
    $top.tex45 configure -font "TkTextFont"
    $top.tex45 insert end text
    vTcl:DefineAlias "$top.tex45" "UserDetails" vTcl:WidgetProc "Teacher_first" 1
    text $top.tex46 \
        -background white -font TkTextFont -foreground black -height 64 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 174 -wrap word 
    $top.tex46 configure -font "TkTextFont"
    $top.tex46 insert end text
    vTcl:DefineAlias "$top.tex46" "ClassDetails" vTcl:WidgetProc "Teacher_first" 1
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 335 -width 295 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Teacher_first" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab48 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Schedule 
    vTcl:DefineAlias "$site_3_0.lab48" "LabelFrame" vTcl:WidgetProc "Teacher_first" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Send 
    vTcl:DefineAlias "$site_3_0.but49" "Btn_Send" vTcl:WidgetProc "Teacher_first" 1
    bind $site_3_0.but49 <Button-1> {
        lambda e: Send_Click(e)
    }
    entry $site_3_0.ent50 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 94 
    vTcl:DefineAlias "$site_3_0.ent50" "Date" vTcl:WidgetProc "Teacher_first" 1
    label $site_3_0.lab51 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Date 
    vTcl:DefineAlias "$site_3_0.lab51" "Label1" vTcl:WidgetProc "Teacher_first" 1
    entry $site_3_0.ent52 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 94 
    vTcl:DefineAlias "$site_3_0.ent52" "Time" vTcl:WidgetProc "Teacher_first" 1
    label $site_3_0.lab53 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Time 
    vTcl:DefineAlias "$site_3_0.lab53" "Label2" vTcl:WidgetProc "Teacher_first" 1
    entry $site_3_0.ent54 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 94 
    vTcl:DefineAlias "$site_3_0.ent54" "ClassType" vTcl:WidgetProc "Teacher_first" 1
    label $site_3_0.lab55 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Type 
    vTcl:DefineAlias "$site_3_0.lab55" "Label3" vTcl:WidgetProc "Teacher_first" 1
    label $site_3_0.lab56 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Content 
    vTcl:DefineAlias "$site_3_0.lab56" "Label4" vTcl:WidgetProc "Teacher_first" 1
    entry $site_3_0.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 94 
    vTcl:DefineAlias "$site_3_0.ent57" "Content" vTcl:WidgetProc "Teacher_first" 1
    button $site_3_0.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Exit 
    vTcl:DefineAlias "$site_3_0.but63" "Btn_Exit" vTcl:WidgetProc "Teacher_first" 1
    bind $site_3_0.but63 <Button-1> {
        lambda e: Exit_Click(e)
    }
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.339 -y 0 -rely 0.03 -width 0 \
        -relwidth 0.329 -height 0 -relheight 0.084 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.407 -y 0 -rely 0.657 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 0 -relx 0.373 -y 0 -rely 0.149 -width 94 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.169 -y 0 -rely 0.119 -width 0 \
        -relwidth 0.149 -height 0 -relheight 0.122 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 0 -relx 0.373 -y 0 -rely 0.269 -width 94 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.169 -y 0 -rely 0.239 -width 0 \
        -relwidth 0.149 -height 0 -relheight 0.122 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 0 -relx 0.373 -y 0 -rely 0.388 -width 94 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.169 -y 0 -rely 0.358 -width 0 \
        -relwidth 0.149 -height 0 -relheight 0.122 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.169 -y 0 -rely 0.478 -width 0 \
        -relwidth 0.149 -height 0 -relheight 0.122 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent57 \
        -in $site_3_0 -x 0 -relx 0.373 -y 0 -rely 0.507 -width 94 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but63 \
        -in $site_3_0 -x 0 -relx 0.407 -y 0 -rely 0.806 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra59 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 335 -width 275 
    vTcl:DefineAlias "$top.fra59" "Frame2" vTcl:WidgetProc "Teacher_first" 1
    set site_3_0 $top.fra59
    label $site_3_0.lab60 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Chat 
    vTcl:DefineAlias "$site_3_0.lab60" "LabelFrame1" vTcl:WidgetProc "Teacher_first" 1
    text $site_3_0.tex61 \
        -background white -font TkTextFont -foreground black -height 284 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 239 -wrap word 
    $site_3_0.tex61 configure -font "TkTextFont"
    $site_3_0.tex61 insert end text
    vTcl:DefineAlias "$site_3_0.tex61" "Chat" vTcl:WidgetProc "Teacher_first" 1
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.364 -y 0 -rely 0.03 -width 0 \
        -relwidth 0.251 -height 0 -relheight 0.063 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex61 \
        -in $site_3_0 -x 0 -relx 0.073 -y 0 -rely 0.119 -width 0 \
        -relwidth 0.869 -height 0 -relheight 0.848 -anchor nw \
        -bordermode ignore 
    label $top.lab62 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Label 
    vTcl:DefineAlias "$top.lab62" "Title" vTcl:WidgetProc "Teacher_first" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tex45 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.022 -width 0 -relwidth 0.273 \
        -height 0 -relheight 0.142 -anchor nw -bordermode ignore 
    place $top.tex46 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.022 -width 0 -relwidth 0.29 \
        -height 0 -relheight 0.142 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.483 -y 0 -rely 0.178 -width 0 -relwidth 0.492 \
        -height 0 -relheight 0.744 -anchor nw -bordermode ignore 
    place $top.fra59 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.178 -width 0 -relwidth 0.458 \
        -height 0 -relheight 0.744 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.044 -width 0 -relwidth 0.157 \
        -height 0 -relheight 0.091 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

