#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Mar 01, 2021 05:06:52 PM +0200  platform: Windows NT
#    Mar 01, 2021 05:09:45 PM +0200  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    global LogIn       
    LogIn = args[1] 
    LogIn.withdraw()
def Exit_Click(p1):
    print('Teacher_support.Exit_Click')
    sys.stdout.flush()
    destroy_window()
def Send_Click(p1):
    print('Teacher_support.Send_Click')
    sys.stdout.flush()
    
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Teacher
    Teacher.vp_start_gui()





